In [83]:
# Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from census import Census
import json
import pprint

# Census API Key
api_key="7fb48d43cd6916b05a4f4b36851852f652fe4c47"
#from config import api_key
c = Census(api_key, year=2013)

base_url= "https://api.census.gov/data/2014/cbp?"
#years=[2014,2015,2016,2017]
#for year in years:
query_url= f"https://api.census.gov/data/{years}/cbp?get=COUNTY,EMP,EMPSZES,EMPSZES_TTL,PAYANN,YEAR&for=county:*&in=state:06&NAICS2012=4853&key=7fb48d43cd6916b05a4f4b36851852f652fe4c47"
response= requests.get(query_url).json()

#https://api.census.gov/data/2012/cbp?get=EMPSZES_TTL,GEO_ID,EMP,ESTAB,NAICS2012_TTL,LFO_TTL,GEO_TTL&for=county:*&in=state:*&key=7fb48d43cd6916b05a4f4b36851852f652fe4c47

response= requests.get(query_url).json()
response
#pprint(json.dumps(response, indent=4, sort_keys=True))

[['COUNTY',
  'EMP',
  'EMPSZES',
  'EMPSZES_TTL',
  'PAYANN',
  'YEAR',
  'NAICS2012',
  'state',
  'county'],
 ['001',
  '271',
  '001',
  'All establishments',
  '7565',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['001',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '001'],
 ['007', '0', '001', 'All establishments', '172', '2014', '4853', '06', '007'],
 ['007',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['007',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['007',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['007',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['007',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['007',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['007',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['007',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['007',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '007'],
 ['009', '0', '001', 'All establishments', '0', '2014', '4853', '06', '009'],
 ['009',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['009',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['009',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['009',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['009',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['009',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['009',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['009',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['009',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '009'],
 ['013',
  '120',
  '001',
  'All establishments',
  '2934',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['013',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '013'],
 ['017', '0', '001', 'All establishments', '0', '2014', '4853', '06', '017'],
 ['017',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['017',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['017',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['017',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['017',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['017',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['017',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['017',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['017',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '017'],
 ['019',
  '161',
  '001',
  'All establishments',
  '4623',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['019',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '019'],
 ['025', '0', '001', 'All establishments', '0', '2014', '4853', '06', '025'],
 ['025',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['025',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['025',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['025',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['025',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['025',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['025',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['025',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['025',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '025'],
 ['029', '0', '001', 'All establishments', '0', '2014', '4853', '06', '029'],
 ['029',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['029',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['029',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['029',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['029',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['029',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['029',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['029',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['029',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '029'],
 ['031', '0', '001', 'All establishments', '0', '2014', '4853', '06', '031'],
 ['031',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['031',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['031',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['031',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['031',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['031',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['031',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['031',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['031',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '031'],
 ['037',
  '2940',
  '001',
  'All establishments',
  '110568',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['037',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '037'],
 ['039', '0', '001', 'All establishments', '0', '2014', '4853', '06', '039'],
 ['039',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['039',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['039',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['039',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['039',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['039',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['039',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['039',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['039',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '039'],
 ['041',
  '74',
  '001',
  'All establishments',
  '1683',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['041',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '041'],
 ['047', '0', '001', 'All establishments', '0', '2014', '4853', '06', '047'],
 ['047',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['047',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['047',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['047',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['047',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['047',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['047',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['047',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['047',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '047'],
 ['053', '0', '001', 'All establishments', '0', '2014', '4853', '06', '053'],
 ['053',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['053',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['053',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['053',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['053',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['053',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['053',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['053',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['053',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '053'],
 ['055',
  '192',
  '001',
  'All establishments',
  '5807',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['055',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '055'],
 ['057', '0', '001', 'All establishments', '72', '2014', '4853', '06', '057'],
 ['057',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['057',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['057',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['057',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['057',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['057',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['057',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['057',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['057',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '057'],
 ['059',
  '583',
  '001',
  'All establishments',
  '14865',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '254',
  'Establishments with 500 to 999 employees',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['059',
  '0',
  '260',
  'Establishments with 1,000 employees or more',
  '0',
  '2014',
  '4853',
  '06',
  '059'],
 ['061', '0', '001', 'All establishments', '193', '2014', '4853', '06', '061'],
 ['061',
  '0',
  '212',
  'Establishments with 1 to 4 employees',
  '0',
  '2014',
  '4853',
  '06',
  '061'],
 ['061',
  '0',
  '220',
  'Establishments with 5 to 9 employees',
  '0',
  '2014',
  '4853',
  '06',
  '061'],
 ['061',
  '0',
  '230',
  'Establishments with 10 to 19 employees',
  '0',
  '2014',
  '4853',
  '06',
  '061'],
 ['061',
  '0',
  '241',
  'Establishments with 20 to 49 employees',
  '0',
  '2014',
  '4853',
  '06',
  '061'],
 ['061',
  '0',
  '242',
  'Establishments with 50 to 99 employees',
  '0',
  '2014',
  '4853',
  '06',
  '061'],
 ['061',
  '0',
  '251',
  'Establishments with 100 to 249 employees',
  '0',
  '2014',
  '4853',
  '06',
  '061'],
 ['061',
  '0',
  '252',
  'Establishments with 250 to 499 employees',
  '0',

In [112]:
#df=pd.DataFrame({dfa[0]:dfa})
county=[]
emp=[]
emp_size=[]
annual_pay=[]
county_id=[]
for i in range(1,len(response)):
    if response[i][1] != "0":
        county.append(response[i][0])
        emp.append(response[i][1])
        emp_size.append(response[i][2])
        annual_pay.append(response[i][4])
        county_id.append(response[i][8])
df_2016= pd.DataFrame({"County":county ,
                        "EMP": emp ,
                        "EMP_SIZE": emp_size ,
                        "Annual_Pay": annual_pay ,
                        "County_id": county_id 
                        })
df_2016.head()

  County   EMP EMP_SIZE Annual_Pay County_id
0    001   271      001       7565       001
1    013   120      001       2934       013
2    019   161      001       4623       019
3    037  2940      001     110568       037
4    041    74      001       1683       041

In [21]:
# Store filepath in a variable
file_counties_2014 = "2014 all counties data.csv"
file_counties_2015 = "2015 all counties data.csv"
file_counties_2016 = "2016 all counties data.csv"
file_counties_2017 = "2017 all counties data.csv"

In [3]:
counties_2014_df=pd.read_csv(file_counties_2014)
counties_2015_df=pd.read_csv(file_counties_2015)
counties_2016_df=pd.read_csv(file_counties_2016)
counties_2017_df=pd.read_csv(file_counties_2017)

In [4]:
#counties_2014_df.head()
counties_2014_sd_df=counties_2014_df.loc[(counties_2014_df["area_fips"] == "6073") | (
    counties_2014_df["area_fips"] == "C4174"), :]

counties_2014_sd_df.count()
counties_2014_sd_df=counties_2014_sd_df[["area_fips","year","annual_avg_estabs","annual_avg_emplvl","annual_avg_wkly_wage","avg_annual_pay"]]
counties_2014_sd_df.head()

,area_fips,year,annual_avg_estabs,annual_avg_emplvl,annual_avg_wkly_wage,avg_annual_pay
80,6073,2014,80,622,485,25206
1444,C4174,2014,80,622,485,25206

In [5]:
counties_2015_sd_df=counties_2015_df.loc[(counties_2015_df["area_fips"] == "6073") | (
    counties_2015_df["area_fips"] == "C4174"), :]

counties_2015_sd_df.count()
counties_2015_sd_df=counties_2015_sd_df[["area_fips","year","annual_avg_estabs","annual_avg_emplvl","annual_avg_wkly_wage","avg_annual_pay"]]
counties_2015_sd_df.head()

,area_fips,year,annual_avg_estabs,annual_avg_emplvl,annual_avg_wkly_wage,avg_annual_pay
77,6073,2015,76,736,531,27619
1434,C4174,2015,76,736,531,27619

In [6]:
counties_2016_df.head()

,area_fips,own_code,industry_code,agglvl_code,size_code,year,qtr,disclosure_code,annual_avg_estabs,annual_avg_emplvl,...,oty_total_annual_wages_chg,oty_total_annual_wages_pct_chg,oty_taxable_annual_wages_chg,oty_taxable_annual_wages_pct_chg,oty_annual_contributions_chg,oty_annual_contributions_pct_chg,oty_annual_avg_wkly_wage_chg,oty_annual_avg_wkly_wage_pct_chg,oty_avg_annual_pay_chg,oty_avg_annual_pay_pct_chg
0,1000,5,4853,56,0,2016,A,NaN,36,197,...,21900,0.5,-26129,-1.4,-7287,-27.3,15,3.9,775,3.9
1,1001,5,4853,76,0,2016,A,N,2,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,1003,5,4853,76,0,2016,A,N,3,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
3,1033,5,4853,76,0,2016,A,N,0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
4,1043,5,4853,76,0,2016,A,N,1,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

In [7]:
counties_2017_df.head()

,area_fips,own_code,industry_code,agglvl_code,size_code,year,qtr,disclosure_code,annual_avg_estabs,annual_avg_emplvl,...,oty_total_annual_wages_chg,oty_total_annual_wages_pct_chg,oty_taxable_annual_wages_chg,oty_taxable_annual_wages_pct_chg,oty_annual_contributions_chg,oty_annual_contributions_pct_chg,oty_annual_avg_wkly_wage_chg,oty_annual_avg_wkly_wage_pct_chg,oty_avg_annual_pay_chg,oty_avg_annual_pay_pct_chg
0,1000,5,4853,56,0,2017,A,NaN,36,193,...,-329992,-8.1,-100963,-5.3,927,4.8,-25,-6.3,-1301,-6.3
1,1001,5,4853,76,0,2017,A,N,2,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,1003,5,4853,76,0,2017,A,N,3,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
3,1033,5,4853,76,0,2017,A,N,1,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
4,1051,5,4853,76,0,2017,A,N,1,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

In [8]:
file_sd_2014 = "2014 San Diego Data.csv"
file_sd_2015 = "2015 San Diego Data.csv"
file_sd_2016 = "2016 San Diego Data.csv"
file_sd_2017 = "2017 San Diego Data.csv"

In [9]:
sd_2014_df=pd.read_csv(file_sd_2014)
sd_2015_df=pd.read_csv(file_sd_2015)
sd_2016_df=pd.read_csv(file_sd_2016)
sd_2017_df=pd.read_csv(file_sd_2017)

In [10]:
#sd_2014_df.head()


sd_2014_df=sd_2014_df.loc[(sd_2014_df["industry_code"] == "4853") | (
    sd_2014_df["industry_code"] == "48531") |(sd_2014_df["industry_code"] == "485310"), :]
sd_2014_df.count()
sd_2014_df=sd_2014_df[["area_fips","industry_code","year","annual_avg_estabs","annual_avg_emplvl","annual_avg_wkly_wage","avg_annual_pay"]]
sd_2014_df.head()

,area_fips,industry_code,year,annual_avg_estabs,annual_avg_emplvl,annual_avg_wkly_wage,avg_annual_pay
1610,6073,4853,2014,80,622,485,25206
1611,6073,48531,2014,20,95,385,20030
1612,6073,485310,2014,20,95,385,20030

In [11]:
sd_2015_df=sd_2015_df.loc[(sd_2015_df["industry_code"] == "4853") | (
    sd_2015_df["industry_code"] == "48531") |(sd_2015_df["industry_code"] == "485310"), :]
sd_2015_df=sd_2015_df[["area_fips","industry_code","year","annual_avg_estabs","annual_avg_emplvl","annual_avg_wkly_wage","avg_annual_pay"]]
sd_2015_df.head()

,area_fips,industry_code,year,annual_avg_estabs,annual_avg_emplvl,annual_avg_wkly_wage,avg_annual_pay
1609,6073,4853,2015,76,736,531,27619
1610,6073,48531,2015,22,125,519,26995
1611,6073,485310,2015,22,125,519,26995

In [12]:
sd_2016_df=sd_2016_df.loc[(sd_2016_df["industry_code"] == "4853") | (
    sd_2016_df["industry_code"] == "48531") |(sd_2016_df["industry_code"] == "485310"), :]
sd_2016_df=sd_2016_df[["area_fips","industry_code","year","annual_avg_estabs","annual_avg_emplvl","annual_avg_wkly_wage","avg_annual_pay"]]
sd_2016_df.head()

,area_fips,industry_code,year,annual_avg_estabs,annual_avg_emplvl,annual_avg_wkly_wage,avg_annual_pay
1596,6073,4853,2016,71,675,510,26507
1597,6073,48531,2016,20,97,520,27018
1598,6073,485310,2016,20,97,520,27018

In [13]:
sd_2017_df=sd_2017_df.loc[(sd_2017_df["industry_code"] == "4853") | (
    sd_2017_df["industry_code"] == "48531") |(sd_2017_df["industry_code"] == "485310")|(sd_2017_df["industry_code"] == "48532")|(sd_2017_df["industry_code"] == "485320"), :]
sd_2017_df=sd_2017_df[["area_fips","industry_code","year","annual_avg_estabs","annual_avg_emplvl","annual_avg_wkly_wage","avg_annual_pay"]]
sd_2017_df.head()

,area_fips,industry_code,year,annual_avg_estabs,annual_avg_emplvl,annual_avg_wkly_wage,avg_annual_pay
1608,6073,4853,2017,77,614,541,28142
1609,6073,48531,2017,22,103,527,27413
1610,6073,485310,2017,22,103,527,27413
1611,6073,48532,2017,55,511,544,28290
1612,6073,485320,2017,55,511,544,28290